const {
  REACT_APP_BEARER_TOKEN,
  REACT_APP_CLIENT_ID,
  REACT_APP_TWITCH_API_BASE_URL,
  REACT_APP_IGDB_API_BASE_URL,
  REACT_APP_PARENT_DOMAIN,
} = process.env;

const config = {
  BEARER_TOKEN: REACT_APP_BEARER_TOKEN,
  CLIENT_ID: REACT_APP_CLIENT_ID,
  TWITCH_API_BASE_URL: REACT_APP_TWITCH_API_BASE_URL,
  IGDB_API_BASE_URL: REACT_APP_IGDB_API_BASE_URL,
  PARENT_DOMAIN: REACT_APP_PARENT_DOMAIN,
};

export default config;
